### PR TITLE
dynamic routing fix

### LINKED ISSUE #214: Next.js dynamic routing fix
## Feature description 

Found the correct way of doing dynamic routing and redirecting with Next.js `Link` component.

File structure with dynamic routing under `/pages/` directory:
https://github.com/vercel/vercel/issues/3294#issuecomment-739250378

Referencing dynamic routes or variables with `Link` componenet:
https://github.com/vercel/vercel/issues/3294#issuecomment-666575214
https://github.com/mattcarlotta/nextjs-basic-data-fetch/blob/master/pages/index.js

Pushing the dynamic link with new query (e.g., page numbers...)
https://github.com/vercel/vercel/issues/3294#issuecomment-592303143

### PR DESCRIPTION
**Pull request by rachelhox**
## Description

closes #214 

## Checklist
- [x] Targeted PR against correct branch.
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

File: src/components/noSSR/index.tsx [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+  }, [defer]);
+
+  useEffect(() => {
+    if (defer) setMountedState(true);
+  }, [defer]);
+
+  return isMounted ? children : fallback;
+};
+
+NoSSR.propTypes = {
```
Comment (kwunyeung) [inline src/components/noSSR/index.tsx:23]: You should create types instead of using proptypes in Typescript.

**Review by kwunyeung — CHANGES_REQUESTED** [review]

**Review by kwunyeung — APPROVED** [review]
